name: Make keystore

on: workflow_dispatch

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Generate debug keystore
        run: |
          keytool -genkeypair -v \
            -keystore debug.keystore \
            -storepass android -alias androiddebugkey -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug, O=Android, C=US"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: debug.keystore